name: verify

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: add atcoder libary
      run: |
        ls
        pwd

    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Run tests
      run: oj-verify all
